name: DBaaS Integration Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create kind config
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
            - role: worker
          EOF

      - name: Set up Kind
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind
          config: kind-config.yaml

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create namespace minio
        run: |
          kubectl create namespace minio \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Create MinIO env secret
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: minio-env
            namespace: minio
          type: Opaque
          stringData:
            config.env: |
              export MINIO_ROOT_USER=minio
              export MINIO_ROOT_PASSWORD=minio123
          EOF

      - name: Apply MinIO operator
        run: |
          kubectl kustomize "github.com/minio/operator?ref=v7.1.1" \
          | kubectl apply -f -

      - name: Wait for MinIO operator
        run: kubectl wait -n minio-operator --for=condition=Available deployment/minio-operator --timeout=300s

      - name: Deploy MinIO Tenant
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: minio.min.io/v2
          kind: Tenant
          metadata:
            name: test-minio
            namespace: minio
          spec:
            configuration:
              name: minio-env
            requestAutoCert: false
            pools:
              - servers: 1
                name: pool-0
                volumesPerServer: 1
                volumeClaimTemplate:
                  metadata:
                    name: data
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 2Gi
          EOF

      - name: Wait for MinIO Tenant readiness
        run: |
          echo "Waiting for MinIO Tenant to become Ready..."
      
          for i in {1..30}; do
            STATE=$(kubectl get tenant test-minio -n minio -o jsonpath='{.status.currentState}')
            echo "Current state: $STATE"
            if [[ "$STATE" == "Ready" || "$STATE" == "Initialized" ]]; then
              echo "MinIO Tenant is ready"
              exit 0
            fi
            sleep 10
          done
      
          echo "MinIO Tenant did not become ready in time"
          exit 1

      - name: Checkout Netcracker/qubership-core-bootstrap repo
        uses: actions/checkout@v4
        with:
          repository: Netcracker/qubership-core-bootstrap
          path: core-bootstrap-repo

      - name: Deploy DBaaS
        working-directory: core-bootstrap-repo/cloud-core-local-dev/dbaas
        run: make install CONFIG_FILE=local.mk


  
