---
name: Maven, Docker & Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: netcracker/qubership-core-infra/.github/workflows/java-service-release.yaml@v1.1.0
    with:
      version: "${{ inputs.version }}"
      dry-run: ${{ inputs.dry-run }}
