---
name: Maven build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/maven-build-with-sonar.yaml@024527ca0ec0b81dcdb6cd31448560293808628a # v1.2.1
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
      upload-artifact: true

  docker-build:
    needs: [mvn]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@024527ca0ec0b81dcdb6cd31448560293808628a # v1.2.1
    with:
      dry-run: false
