---
name: Maven build

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/maven-build-with-sonar.yaml@32a5b506971a029acc41bc69fd42d06137caeb36 # v1.3.3
    with:
      event-name: ${{ github.event_name }}
      actor: ${{ github.actor }}
      upload-artifact: true

  docker-build:
    needs: [mvn]
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@32a5b506971a029acc41bc69fd42d06137caeb36 # v1.3.3
    with:
      dry-run: false
